session_name: exercism
start_directory: ./
shell_command_before:
  - source ./env-exercism.sh
windows:
  - window_name: exercism-workspace
    focus: 'true'
    layout: main-vertical
    options: {}
    panes:
      - pane
      - pane
      - pane
